export const FETCH_USERS_REQUEST_SAGA = "FETCH_USERS_REQUEST_SAGA";
export const FETCH_USERS_SUCCESS_SAGA = "FETCH_USERS_SUCCESS_SAGA";
export const FETCH_USERS_FAILURE_SAGA = "FETCH_USERS_FAILURE_SAGA";
